name: Build, Test, and Deploy Docker Image to Quay.io

on:
  pull_request:
    paths:
      - Dockerfile
      - conda/environment.yml
      - bin/*
      - data/*
      - assets/*
      - tests/*
  push:
    tags:
      - '[1-9]+.[0-9]+.[0-9]+' # Only deploy on tags with semantic versioning
      - '[1-9]+.[0-9]+.[0-9]+-[a-z]+' # Only deploy on tags with semantic versioning
      - 'v[1-9]+.[0-9]+.[0-9]+' # Only deploy on tags with semantic versioning
      - 'v[1-9]+.[0-9]+.[0-9]+-[a-z]+' # Only deploy on tags with semantic versioning
    branches:
      - main
  release:
    types: [published]

env:
    QUAY_SERVER: ${{ secrets.QUAY_SERVER }}
    QUAY_NAMESPACE: ${{ secrets.QUAY_NAMESPACE }}
    QUAY_ROBOT_ID: ${{ secrets.QUAY_ROBOT_ID }}
    QUAY_ROBOT_TOKEN: ${{ secrets.QUAY_ROBOT_TOKEN }}

jobs:
  build-and-deploy:

    runs-on: ubuntu-22.04

    steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Extract container name, version, and build date
          run: |
            CONTAINER_NAME=$(python get_container_name.py)
            VERSION=$(python get_version.py)
            BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
            echo "CONTAINER_NAME=$CONTAINER_NAME" >> $GITHUB_ENV
            echo "VERSION=$VERSION" >> $GITHUB_ENV
            echo "BUILD_DATE=$BUILD_DATE" >> $GITHUB_ENV

        - name: Set image name and test tag
          run: |
            IMAGE_NAME=${QUAY_SERVER}/${QUAY_NAMESPACE}/${CONTAINER_NAME}
            TEST_TAG=${IMAGE_NAME}:${VERSION}-test
            echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
            echo "TEST_TAG=$TEST_TAG" >> $GITHUB_ENV

        - name: Docker meta
          id: meta
          uses: docker/metadata-action@v5.5.1
          with:
            images: ${{ env.IMAGE_NAME }}

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Login to Quay.io
          uses: docker/login-action@v3
          with:
            registry: ${{ env.QUAY_SERVER }}
            username: ${{ env.QUAY_ROBOT_ID }}
            password: ${{ env.QUAY_ROBOT_TOKEN }}

        - name: Build and export to Quay.io
          uses: docker/build-push-action@v5
          with:
            context: .
            load: true
            tags: ${{ env.TEST_TAG }}
            build-args: |
              VERSION=${{ env.VERSION }}
              BUILD_DATE=${{ env.BUILD_DATE }}
              VCS_REF=${{ github.sha }}
            provenance: false

        - name: Test
          run: |
            docker run --rm $TEST_TAG \
                micromamba run -n base \
                python tests/test_print_version.py

        - name: Build and push
          uses: docker/build-push-action@v5
          with:
            context: .
            file: ./Dockerfile
            push: true
            tags: ${{ steps.meta.outputs.tags }}
            build-args: |
              VERSION=${{ env.VERSION }}
              BUILD_DATE=${{ env.BUILD_DATE }}
              VCS_REF=${{ github.sha }}
            provenance: false